### ISSUE TITLE
I believe I may be missing something.

### ISSUE THREAD

**Issue by databoy** [MakeSchool-Tutorials/Make-School-iOS-Development-Course#4]
I like the tutorial so far. It's a great start to an lofty goal!

In Step 3, 'https://www.makeschool.com/tutorials/advanced-ios-development/server-flask' and at the line "You should have access to the starter project through GitHub Classroom." I'm missing how I "should have access."

I watched the lecture and looked through the slides, but didn't see the obvious solution of cloning to my local machine the Git repo https://github.com/MakeSchool-17/trip-planner-flask-backend-databoy that was created when I followed the link "Start the assignment by using this link." (https://classroom.github.com/assignment-invitations/cc2a161b4fb90279ae2620d13f22431c)

That is, before I follow the instructions to "Create a new virtual environment, in the root folder of the starter project..." I need to--you know--actually get the starter project. I think I can figure it out, but if I have problems, I'll post them here.

**Comment by databoy** [comment]
Creating a virtual environment failed. 

Machine:flask chris$ virtualenv -p python3 development
-bash: virtualenv: command not found

I missed yet another step (or requirement)? Honestly, I was just going to add a "service" to my Drupal site to get the endpoints and RESTful support for the rest of the tutorial. But, I thought, I'll just follow the steps as written and then analyze the results...

**Comment by dionlarson** [comment]
This tutorial needs to be a bit more generalized. It currently assumes you are a Make School student and have gone through the previous curriculum (including environment setup for Python). I believe [this](https://github.com/MakeSchool-Tutorials/MS-2017-Environment-Installation/blob/master/P2-Python-Install-Instructions/content.md) should get you up and running.

**Comment by databoy** [comment]
Thanks! That's what I needed to continue.
